### ISSUE TITLE
Does not build with libvips v7.38.1

### ISSUE THREAD

**Issue by ahacking** [libvips/ruby-vips#48]
Installing the gem results in the following error

```
creating Makefile

make "DESTDIR="
compiling header.c
compiling image.c
compiling image_arithmetic.c
compiling image_boolean.c
compiling image_colour.c
compiling image_conversion.c
compiling image_convolution.c
compiling image_freq_filt.c
image_freq_filt.c: In function ‘img_s_fmask_ideal_highpass’:
image_freq_filt.c:123: error: ‘VIPS_MASK_IDEAL_HIGHPASS’ undeclared (first use in this function)
image_freq_filt.c:123: error: (Each undeclared identifier is reported only once
image_freq_filt.c:123: error: for each function it appears in.)
image_freq_filt.c: In function ‘img_s_fmask_ideal_lowpass’:
image_freq_filt.c:144: error: ‘VIPS_MASK_IDEAL_LOWPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_butterworth_highpass’:
image_freq_filt.c:165: error: ‘VIPS_MASK_BUTTERWORTH_HIGHPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_butterworth_lowpass’:
image_freq_filt.c:187: error: ‘VIPS_MASK_BUTTERWORTH_LOWPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_gauss_highpass’:
image_freq_filt.c:209: error: ‘VIPS_MASK_GAUSS_HIGHPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_gauss_lowpass’:
image_freq_filt.c:231: error: ‘VIPS_MASK_GAUSS_LOWPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_ideal_ringpass’:
image_freq_filt.c:252: error: ‘VIPS_MASK_IDEAL_RINGPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_ideal_ringreject’:
image_freq_filt.c:273: error: ‘VIPS_MASK_IDEAL_RINGREJECT’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_butterworth_ringpass’:
image_freq_filt.c:295: error: ‘VIPS_MASK_BUTTERWORTH_RINGPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_butterworth_ringreject’:
image_freq_filt.c:318: error: ‘VIPS_MASK_BUTTERWORTH_RINGREJECT’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_gauss_ringpass’:
image_freq_filt.c:341: error: ‘VIPS_MASK_GAUSS_RINGPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_gauss_ringreject’:
image_freq_filt.c:363: error: ‘VIPS_MASK_GAUSS_RINGREJECT’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_ideal_bandpass’:
image_freq_filt.c:385: error: ‘VIPS_MASK_IDEAL_BANDPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_ideal_bandreject’:
image_freq_filt.c:408: error: ‘VIPS_MASK_IDEAL_BANDREJECT’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_butterworth_bandpass’:
image_freq_filt.c:432: error: ‘VIPS_MASK_BUTTERWORTH_BANDPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_butterworth_bandreject’:
image_freq_filt.c:456: error: ‘VIPS_MASK_BUTTERWORTH_BANDREJECT’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_gauss_bandpass’:
image_freq_filt.c:480: error: ‘VIPS_MASK_GAUSS_BANDPASS’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_gauss_bandreject’:
image_freq_filt.c:504: error: ‘VIPS_MASK_GAUSS_BANDREJECT’ undeclared (first use in this function)
image_freq_filt.c: In function ‘img_s_fmask_fractal_flt’:
image_freq_filt.c:528: error: ‘VIPS_MASK_FRACTAL_FLT’ undeclared (first use in this function)
make: *** [image_freq_filt.o] Error 1
```

It seems the above #defines have been deprecated in recent versions of VIPS and changing them to IM_MASK_XXX resolves the issue.
